# fly.toml app configuration file generated for qa-system on 2025-04-18T00:02:11-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'qa-system'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source = "data_volume"
  destination = "/app/data"


[[vm]]
  size = 'shared-cpu-1x'
